services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn travel_app_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      celery -A travel_app_backend worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: travel_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - backend    

volumes:
  pgdata:
